### ISSUE TITLE
Theme not working on abp version 4.0 

### ISSUE THREAD

**Issue by MROALI** [EasyAbp/Abp.AspNetCore.Mvc.UI.Theme.LYear#1]
Hello,
i tried running the theme LYear on sample bookstore version  in abp 4.0 without success.
i am getting the following error : 
TypeLoadException: Could not load type 'Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Components.IBrandingProvider' from assembly 'Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.

any idea how to fix that ?

**Comment by MROALI** [comment]
Any news about updating the theme to be compatible with version 4.0 of abp ?

**Comment by hueifeng** [comment]
@MROALI Modules of EasyAbp will be upgraded to ABP 4.0+ in mid December if the new version of the framework is as stable as expected.
